title: Commands
description: Command line cheat sheet
theme: jekyll-theme-clyell
theme_mode:  [light|dark]
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
layout: page
title: "Linux Commands"
premalink: /commands0
